name: GitHub Metrics Manual
on:
  workflow_dispatch: 

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: theclumsypirate
          template: classic
          
          # 'base: header, activity, repositories, packages'
          # Aceasta activează doar statisticile globale, nu și feed-ul de evenimente recente
          base: header, activity, repositories, packages
          
          # BLOCĂM tot ce este social și metadata (Last updated)
          base_metadata: no
          repositories_stats: no
          
          # Dezactivăm feed-ul de "Recent Activity" (cel care arată ce ai făcut acum x ore)
          # Dar păstrăm cifrele de activitate din 'base'
          plugin_activity: no
          
          # Design și Culori
          config_timezone: Europe/Bucharest
          theme: tokyonight
          filename: github-metrics.svg
